language: node_js
node_js:
- "v12.18.2"
script:
- echo "Deploying!"
- npm install
install:
- npm install -g firebase-tools
after_success:
- firebase deploy --token 1//0dwNsjYunf8ywCgYIARAAGA0SNgF-L9Ir0LjI6zDE89bqYuJDtOnKh8yvU3kBw37gbDyLf7lMZLv2hcEFg7xMNPbwKqfU-Xme6A